DEBUG 2016-07-26 17:07:18,735: 	 Executing command: 'status'
DEBUG 2016-07-26 17:07:18,736: 	 Found CRAB cache file /afs/cern.ch/user/f/fromeo/.crab3
ERROR 2016-07-26 17:07:18,737: 	 Error: Full2202_SEle_16Dec2015C_JsonGold/crab_Full2202_SEle_16Dec2015C_JsonGold is not a valid CRAB project directory.
ERROR 2016-07-26 17:07:18,737: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 749, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: Full2202_SEle_16Dec2015C_JsonGold/crab_Full2202_SEle_16Dec2015C_JsonGold is not a valid CRAB project directory.
DEBUG 2016-07-26 17:07:19,350: 	 Executing command: 'status'
DEBUG 2016-07-26 17:07:19,350: 	 Found CRAB cache file /afs/cern.ch/user/f/fromeo/.crab3
ERROR 2016-07-26 17:07:19,350: 	 Error: Full2202_SMu_16Dec2015C_JsonGold/crab_Full2202_SMu_16Dec2015C_JsonGold is not a valid CRAB project directory.
ERROR 2016-07-26 17:07:19,350: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 749, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: Full2202_SMu_16Dec2015C_JsonGold/crab_Full2202_SMu_16Dec2015C_JsonGold is not a valid CRAB project directory.
DEBUG 2016-07-26 19:07:30,574: 	 Executing command: 'status'
DEBUG 2016-07-26 19:07:30,574: 	 Found CRAB cache file /afs/cern.ch/user/f/fromeo/.crab3
DEBUG 2016-07-26 19:07:30,589: 	 Checking credentials
DEBUG 2016-07-26 19:07:30,590: 	 Found proxy file /tmp/x509up_u30997
DEBUG 2016-07-26 19:07:30,590: 	 Getting proxy life time left
DEBUG 2016-07-26 19:07:31,195: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u30997 -timeleft
 output : 75469

 error: 
 retcode : 0
DEBUG 2016-07-26 19:07:31,805: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u30997 -actimeleft
 output : 75469

 error: 
 retcode : 0
DEBUG 2016-07-26 19:07:31,805: 	 Proxy valid for 20:57:49 hours
ERROR 2016-07-26 19:07:31,808: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/f/fromeo/CMSSW_8_0_12_FW/src/BSMFramework/BSM3G_TNT_Maker/crab/First2016_2_WZ/crab_First2016_2_WZ
ERROR 2016-07-26 19:07:31,809: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/f/fromeo/CMSSW_8_0_12_FW/src/BSMFramework/BSM3G_TNT_Maker/crab/First2016_2_WZ/crab_First2016_2_WZ
DEBUG 2016-07-27 11:05:01,031: 	 Executing command: 'status'
DEBUG 2016-07-27 11:05:01,031: 	 Found CRAB cache file /afs/cern.ch/user/f/fromeo/.crab3
DEBUG 2016-07-27 11:05:01,059: 	 Checking credentials
DEBUG 2016-07-27 11:05:01,059: 	 Found proxy file /tmp/x509up_u30997
DEBUG 2016-07-27 11:05:01,059: 	 Getting proxy life time left
DEBUG 2016-07-27 11:05:01,869: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u30997 -timeleft
 output : 86308

 error: 
 retcode : 0
DEBUG 2016-07-27 11:05:02,576: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u30997 -actimeleft
 output : 86306

 error: 
 retcode : 0
DEBUG 2016-07-27 11:05:02,576: 	 Proxy valid for 23:58:28 hours
ERROR 2016-07-27 11:05:02,631: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/f/fromeo/CMSSW_8_0_12_FW/src/BSMFramework/BSM3G_TNT_Maker/crab/First2016_2_WZ/crab_First2016_2_WZ
ERROR 2016-07-27 11:05:02,632: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/f/fromeo/CMSSW_8_0_12_FW/src/BSMFramework/BSM3G_TNT_Maker/crab/First2016_2_WZ/crab_First2016_2_WZ
